### ISSUE TITLE
Catch errors transmitting responses from the Python worker to the Java worker

### ISSUE THREAD

**Issue by carlosuc3m** [apposed/appose#8]
Hello, 
I have a couple of suggestions regarding the transmission of responses from the Python worker to the Java worker.

First for the `Task.update(...)` method at https://github.com/apposed/appose-python/blob/78c0f47ffa3265d7a4e8fbb49b6ef6cc7c540251/src/appose/python_worker.py#L51

The messages are enforced to be Strings on the Java side with an [unchecked casting to String](https://github.com/apposed/appose-java/blob/b527d884f92d1adfbe482c7a33b91bbf7223de2a/src/main/java/org/apposed/appose/Service.java#L314).

The logic of both the Python and Java workers could be made more complex to allow other types of messages but I think that for now, it is reasonable to keep it for Strings only. In that case it would make sense to slightly modify the method as the follwoing to avoid errors that in addition leave the Java worker waiting forever:
```
def update(
    self,
     message: Optional[str] = None,
     current: Optional[int] = None,
     maximum: Optional[int] = None,
) -> None:
    args = {}
    if message is not None and isinstance(message, str):
        args["message"] = message
    elif message is not None:
        raise TypeError(f"Object of type {message.__class__.__name__} cannot be sent as an UPDATE, only str is allowed")
    if current is not None:
        args["current"] = current
    if maximum is not None:
        args["maximum"] = maximum
    self._respond(ResponseType.UPDATE, args)
```
The TypeError raised makes the appose python process to fail and triggering a `FAILURE` event that is listened by the Java worker.

The other suggestion is directly on the `_respond(...)` method at https://github.com/apposed/appose-python/blob/78c0f47ffa3265d7a4e8fbb49b6ef6cc7c540251/src/appose/python_worker.py#L134

When a response cannot be encoded ( for example when one of the outputs cannot be encoded because it is of unsopported types like np.array) an exception is raised, but it does not produce a Task.failure(), which leaves the Java worker waiting forever to the completion of the Python process.
An easy way to solve it would be catching the exception raised if the response cannot be encoded:
```
def _respond(self, response_type: ResponseType, args: Optional[Args]) -> None:
    response = {"task": self.uuid, "responseType": response_type.value}
    if args is not None:
        response.update(args)
    # NB: Flush is necessary to ensure service receives the data!
    try:
        print(encode(response), flush=True)
    except Exception:
        if response_type is ResponseType.UPDATE:
            self.update(traceback.format_exc())
        else:
            self.fail(traceback.format_exc())
```

In the code above (it is what i am using locally) if the response cannot be encoded and the `ResponseType` is not an `UPDATE` a fail event is triggered with the error message that caused it.
If the response was an `UPDATE` it redoes the update but now the message is the error message. Note that increasing the robustness in the `update(...)` method would make ` if response_type is ResponseType.UPDATE:` unnecessary. Furthermore increasing the  robustness in the methods that produce responses would make the `try:...except:...` unnecessary too, but maybe it is not worth the effort.

What do you think?
REgards,
Carlos

**Comment by ctrueden** [comment]
Addressed by the above linked commits.
